#!/usr/bin/env python

# Wiley Educational Services 

import sys, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Enter project code here. This will be used to validate the commit message.
project_code = "EB";

# Open the commit file
with open(commit_msg_filepath, 'r') as f:
    # Read commit
    content = f.read()

    # Valid pattern regex
    pattern = re.compile("^("+project_code+"-[0-9]+) : |:|: [a-zA-Z].+$")

    # Define error message colors
    red='\033[0;31m'
    nc='\033[0m' # No Color
    cyan='\033[0;36m'

    # Check whether the pattern matches
    if not pattern.search(content):

        message="\nPlease adhere to commit message rules. Every commit message should start with the Jira ID and the message followed by a colon.\n"

        example="example: git commit -m \""+project_code+"-123 : This is my commit message\"\n"

        tryagain="Check your commit message and try again.\n"

        print(red)
        print(r"""
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣴⣆⣠⣤⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣻⣿⣯⣘⠹⣧⣤⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠿⢿⣿⣷⣾⣯⠉⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⠜⣿⡍⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⠁⠀⠘⣿⣆⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡟⠃⡄⠀⠘⢿⣆⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣁⣋⣈ ⣤⣮⣿⣧⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣤⣤⣤⣤⣶⣦⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⡿⠛⠉⠙⠛⠛⠛⠛⠻⢿⣿⣷⣤⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⠋⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⠈⢻⣿⣿⡄⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣸⣿⡏⠀⠀⠀⣠⣶⣾⣿⣿⣿⠿⠿⠿⢿⣿⣿⣿⣄⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⠁⠀⠀⢰⣿⣿⣯⠁⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⣷⡄⠀
⠀⠀⣀⣤⣴⣶⣶⣿⡟⠀⠀⠀⢸⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣷⠀
⠀⢰⣿⡟⠋⠉⣹⣿⡇⠀⠀⠀⠘⣿⣿⣿⣿⣷⣦⣤⣤⣤⣶⣶⣶⣶⣿⣿⣿⠀
⠀⢸⣿⡇⠀⠀⣿⣿⡇⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠀
⠀⣸⣿⡇⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠉⠻⠿⣿⣿⣿⣿⡿⠿⠿⠛⢻⣿⡇⠀⠀
⠀⣿⣿⠁⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣧⠀⠀
⠀⣿⣿⠀⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠀⠀
⠀⣿⣿⠀⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠀⠀
⠀⢿⣿⡆⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⠀⠀
⠀⠸⣿⣧⡀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⠃⠀⠀
⠀⠀⠛⢿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⣰⣿⣿⣷⣶⣶⣶⣶⠶⠀⢠⣿⣿⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⠀⠀⠀⣿⣿⡇⠀⣽⣿⡏⠁⠀⠀⢸⣿⡇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⠀⠀⠀⠀⠀⣿⣿⡇⠀⢹⣿⡆⠀⠀⠀⣸⣿⠇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢿⣿⣦⣄⣀⣠⣴⣿⣿⠁⠀⠈⠻⣿⣿⣿⣿⡿⠏⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠛⠻⠿⠿⠿⠿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀



███████ ██████  ██████   ██████  ██████      ██████  ███████ ██████   ██████  ██████  ████████ ███████ ██████  
██      ██   ██ ██   ██ ██    ██ ██   ██     ██   ██ ██      ██   ██ ██    ██ ██   ██    ██    ██      ██   ██ 
█████   ██████  ██████  ██    ██ ██████      ██████  █████   ██████  ██    ██ ██████     ██    █████   ██   ██ 
██      ██   ██ ██   ██ ██    ██ ██   ██     ██   ██ ██      ██      ██    ██ ██   ██    ██    ██      ██   ██ 
███████ ██   ██ ██   ██  ██████  ██   ██     ██   ██ ███████ ██       ██████  ██   ██    ██    ███████ ██████  
                                                                                                               

┌─┐┬ ┬┌─┐┌─┐┬┌─  ┌┬┐┬ ┬┌─┐  ┌─┐┌─┐┌┬┐┌┬┐┬┌┬┐  ┌┬┐┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
│  ├─┤├┤ │  ├┴┐   │ ├─┤├┤   │  │ ││││││││ │   │││├┤ └─┐└─┐├─┤│ ┬├┤ 
└─┘┴ ┴└─┘└─┘┴ ┴   ┴ ┴ ┴└─┘  └─┘└─┘┴ ┴┴ ┴┴ ┴   ┴ ┴└─┘└─┘└─┘┴ ┴└─┘└─┘""")

        print(nc)
        print(message)

        print(cyan)
        print(example)
        print(nc)
        
        print(tryagain)

        # Exit if the pattern does not match
        sys.exit(1)
