name: PHP_CodeSniffer

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          coverage: none
          tools: composer, cs2pr
          
      # we may use whatever way to install phpcs, just specify the path on the next step
      # however, curl seems to be the fastest
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
          
      - name: Set Moodle CS
        uses: actions/checkout@v2
        with:
          repository: moodlehq/moodle-local_codechecker
          ref: v3.0.2
          path: ./.github/actions/moodle-local_codechecker

      - name: Checking with CodeSniffer
        uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php" # you may customize glob as needed
          phpcs_path: php phpcs.phar
          standard: ./.github/actions/moodle-local_codechecker/moodle/ruleset.xml

      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml
      # - name: Detect coding standard violations
      #   run: php phpcs.phar ./ -q --standard=PSR12 --report=checkstyle | cs2pr --graceful-warnings
